-- Supabase Schema for PrintMaster Press

-- 1. Customers Table
CREATE TABLE customers (
  id bigint primary key generated by default as identity,
  name text not null,
  phone text not null,
  email text,
  gst text,
  address text,
  "createdAt" date default CURRENT_DATE
);

-- 2. Orders Table
CREATE TABLE orders (
  id bigint primary key generated by default as identity,
  "customerId" bigint references customers(id),
  "customerName" text,
  "jobType" text,
  qty bigint,
  "paperType" text,
  size text,
  color text,
  instructions text,
  deadline date,
  status text default 'Pending',
  "assignedTo" text,
  amount numeric(10,2),
  "createdAt" date default CURRENT_DATE
);

-- 3. Inventory Table
CREATE TABLE inventory (
  id bigint primary key generated by default as identity,
  name text not null,
  category text,
  qty numeric(10,2) default 0,
  unit text,
  "reorderLevel" numeric(10,2) default 0,
  "costPerUnit" numeric(10,2) default 0,
  "createdAt" date default CURRENT_DATE
);

-- 4. Invoices Table
CREATE TABLE invoices (
  id bigint primary key generated by default as identity,
  "orderId" bigint references orders(id) on delete set null,
  "customerId" bigint references customers(id),
  "customerName" text,
  items jsonb default '[]'::jsonb,
  subtotal numeric(10,2),
  tax numeric(10,2),
  total numeric(10,2),
  status text default 'Unpaid',
  "createdAt" date default CURRENT_DATE
);

-- 5. Enquiries Table
CREATE TABLE enquiries (
  id bigint primary key generated by default as identity,
  name text not null,
  phone text not null,
  email text,
  service text,
  qty text,
  msg text,
  status text default 'New',
  date timestamp with time zone default now()
);

-- 6. Settings Table
CREATE TABLE settings (
  id int primary key default 1,
  "shopName" text,
  "ownerName" text,
  phone text,
  email text,
  address text,
  gst text,
  "taxRate" numeric(5,2),
  currency text,
  terms text,
  "createdAt" timestamp with time zone default now()
);

-- Seed Initial Settings
INSERT INTO settings ("shopName", "ownerName", phone, email, address, gst, "taxRate", currency, terms)
VALUES ('Star Xerox', 'Ashish Kumar', '9162141111', 'starxerox@gmail.com', 'Bihta, Near Railway Station', '', 18, '₹', 'Goods once sold will not be returned.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ROW LEVEL SECURITY (RLS) — Production Policies
-- ============================================================
-- Enable RLS on all tables
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Authenticated users (admin) get full access to all tables
CREATE POLICY "Admin full access on customers" ON customers FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on orders" ON orders FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on inventory" ON inventory FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on invoices" ON invoices FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on enquiries" ON enquiries FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on settings" ON settings FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Anonymous users can INSERT enquiries (contact form from customer website)
CREATE POLICY "Anon can submit enquiries" ON enquiries FOR INSERT WITH CHECK (true);

-- Anonymous users can READ settings (for website display)
CREATE POLICY "Anon can read settings" ON settings FOR SELECT USING (true);

-- 7. Services Table
CREATE TABLE services (
  id bigint primary key generated by default as identity,
  name text not null,
  description text,
  icon text,
  price text,
  color text,
  "createdAt" timestamp with time zone default now()
);

INSERT INTO services (name, description, icon, price, color) VALUES
('Business Cards', 'Premium business cards with matte, glossy, or UV coating. Rounded corners, spot UV, and custom finishes available.', '💼', 'From ₹500/250 cards', '#3b82f6'),
('Pamphlets & Flyers', 'Eye-catching pamphlets for promotions, events, and marketing. Single-fold, bi-fold, and tri-fold options.', '📄', 'From ₹2/piece', '#22c55e'),
('Banners & Flex', 'Large format outdoor flex banners for shops, events, and exhibitions. Weather-resistant & vibrant colors.', '🏳️', 'From ₹40/sq.ft', '#f59e0b'),
('Books & Notebooks', 'Perfect binding, spiral binding, and saddle-stitching for books, manuals, catalogs, and notebooks.', '📚', 'Custom pricing', '#a78bfa'),
('Letterheads & Pads', 'Professional letterheads, note pads, prescription pads with your logo and brand colors. Bulk discounts available.', '🏷️', 'From ₹1.5/sheet', '#06b6d4'),
('Custom Printing', 'Stickers, envelopes, calendars, wedding cards, invitation cards, certificates — you name it, we print it!', '🎨', 'Contact for pricing', '#ec4899');
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon can read services" ON services FOR SELECT USING (true);
CREATE POLICY "Admin full access on services" ON services FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 8. Portfolio Table
CREATE TABLE portfolio (
  id bigint primary key generated by default as identity,
  title text not null,
  icon text,
  color1 text,
  color2 text,
  "createdAt" timestamp with time zone default now()
);

INSERT INTO portfolio (title, icon, color1, color2) VALUES
('Corporate Mugs', '☕', '#ea580c', '#9a3412'),
('Event Banners', '🏳️', '#3b82f6', '#1d4ed8'),
('Premium ID Cards', '💳', '#10b981', '#047857'),
('Custom T-Shirts', '👕', '#8b5cf6', '#5b21b6'),
('Restaurant Menus', '📖', '#f59e0b', '#b45309'),
('Wedding Cards', '💌', '#ec4899', '#be185d');
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon can read portfolio" ON portfolio FOR SELECT USING (true);
CREATE POLICY "Admin full access on portfolio" ON portfolio FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
